group_imports = "StdExternalCrate"
wrap_comments = true
use_try_shorthand = true
use_field_init_shorthand = true
reorder_impl_items = true
normalize_doc_attributes = true
normalize_comments = true
imports_granularity = "Module"
match_block_trailing_comma = true
format_strings = true
format_macro_matchers = true
format_code_in_doc_comments = true
fn_single_line = true
condense_wildcard_suffixes = true
